In [162]:
import pandas as pd
import numpy as np
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [163]:
df1=pd.read_csv('urduDataTrainfold1.txt',header = None,sep = '\t')
df1

0         1
0       لاہور  Location
1           (     Other
2         این     Other
3         این     Other
4         آئی     Other
...       ...       ...
648745     کو     Other
648746   حتمی     Other
648747    شکل     Other
648748     دے     Other
648749     گی     Other

[648750 rows x 2 columns]

In [164]:
df2 = pd.read_csv('urduDataTestfold1.txt',sep = '\t',header = None)
df2

0      1
0              '  Other
1       ولی‌اللہ  Other
2              '  Other
3          پڑھتے  Other
4             ہی  Other
...          ...    ...
277988     نامور  Other
277989    ستاروں  Other
277990        نے  Other
277991      شرکت  Other
277992        کی  Other

[277993 rows x 2 columns]

In [166]:
train_in=df1.iloc[ : , 0].values  #class pr onehotencoder lgy ga
#train_in.reshape(1,-1)
train_in = np.array(train_in).reshape((len(train_in), 1))
hotencoder = OneHotEncoder()
train_in = hotencoder.fit_transform(train_in)
print(train_in)

  (0, 16823)	1.0
  (1, 14)	1.0
  (2, 5951)	1.0
  (3, 5951)	1.0
  (4, 2418)	1.0
  (5, 15)	1.0
  (6, 3213)	1.0
  (7, 21012)	1.0
  (8, 15249)	1.0
  (9, 7684)	1.0
  (10, 15208)	1.0
  (11, 15117)	1.0
  (12, 22237)	1.0
  (13, 25549)	1.0
  (14, 14463)	1.0
  (15, 28646)	1.0
  (16, 27484)	1.0
  (17, 6477)	1.0
  (18, 28193)	1.0
  (19, 29001)	1.0
  (20, 27048)	1.0
  (21, 21759)	1.0
  (22, 21300)	1.0
  (23, 27399)	1.0
  (24, 14012)	1.0
  :	:
  (648725, 14153)	1.0
  (648726, 17663)	1.0
  (648727, 9996)	1.0
  (648728, 15562)	1.0
  (648729, 17963)	1.0
  (648730, 27123)	1.0
  (648731, 8940)	1.0
  (648732, 28192)	1.0
  (648733, 2382)	1.0
  (648734, 9100)	1.0
  (648735, 3582)	1.0
  (648736, 27123)	1.0
  (648737, 12986)	1.0
  (648738, 19483)	1.0
  (648739, 28371)	1.0
  (648740, 6850)	1.0
  (648741, 6046)	1.0
  (648742, 26165)	1.0
  (648743, 5825)	1.0
  (648744, 4297)	1.0
  (648745, 26259)	1.0
  (648746, 9817)	1.0
  (648747, 14584)	1.0
  (648748, 11372)	1.0
  (648749, 28192)	1.0


In [167]:
train_out=df2.iloc[ : , 1 ].values #label pr label encoder lgy ga
labelencode = LabelEncoder()
train_out = labelencode.fit_transform(train_out)
print(train_out)

[2 2 2 ... 2 2 2]


In [169]:
X_train,X_test, y_train,y_test = train_test_split(train_in[0:277993],train_out,test_size=0.2)
X_train = X_train.astype(float)
print(X_train)

  (0, 19031)	1.0
  (1, 27399)	1.0
  (2, 27399)	1.0
  (3, 4083)	1.0
  (4, 19483)	1.0
  (5, 14835)	1.0
  (6, 2382)	1.0
  (7, 3206)	1.0
  (8, 25549)	1.0
  (9, 6684)	1.0
  (10, 12858)	1.0
  (11, 29001)	1.0
  (12, 27142)	1.0
  (13, 29358)	1.0
  (14, 4661)	1.0
  (15, 3560)	1.0
  (16, 21319)	1.0
  (17, 20078)	1.0
  (18, 5951)	1.0
  (19, 4736)	1.0
  (20, 14935)	1.0
  (21, 28237)	1.0
  (22, 2787)	1.0
  (23, 7406)	1.0
  (24, 27123)	1.0
  :	:
  (222369, 22237)	1.0
  (222370, 9817)	1.0
  (222371, 6270)	1.0
  (222372, 3449)	1.0
  (222373, 19483)	1.0
  (222374, 18567)	1.0
  (222375, 2382)	1.0
  (222376, 15746)	1.0
  (222377, 18285)	1.0
  (222378, 25015)	1.0
  (222379, 28089)	1.0
  (222380, 28429)	1.0
  (222381, 3142)	1.0
  (222382, 28994)	1.0
  (222383, 25467)	1.0
  (222384, 20199)	1.0
  (222385, 27399)	1.0
  (222386, 27399)	1.0
  (222387, 22345)	1.0
  (222388, 18)	1.0
  (222389, 26259)	1.0
  (222390, 6237)	1.0
  (222391, 19483)	1.0
  (222392, 15)	1.0
  (222393, 12720)	1.0


In [170]:
model=svm.SVC()

In [171]:
model=model.fit(X_train,y_train)

In [172]:
predicted_labels=model.predict(X_test)

In [173]:
print(accuracy_score(predicted_labels,y_test))

0.9112394107807694


In [174]:
from sklearn.metrics import confusion_matrix

In [175]:
print(confusion_matrix(predicted_labels,y_test))

[[    0     0     2     0]
 [    0     0     3     0]
 [ 2008  1000 50664  1920]
 [    0     0     2     0]]
